version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build:
      context: ./docker/api
    ports:
      - "3000:3000"
    environment:
      DB_ROOT_PASSWORD: password
      DB_DATABASE: books
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
